require("plugins_setup.toggleterm")
require("plugins_setup.treesitter")
require("plugins_setup.other")
require("plugins_setup.telescope")
-- require('plugins_setup.nerdtree')
require("plugins_setup.nvim-tree")
require("plugins_setup.nvim-lspconfig")
require("plugins_setup.mason")
require("plugins_setup.mason-lspconfig")
require("plugins_setup.lualine-nvim")
-- require('plugins_setup.nordic')
-- require('plugins_setup.nightfox')
require("plugins_setup.catppuccin")
require("plugins_setup.lspsaga")
require("plugins_setup.nvim-cmp")
